### ISSUE TITLE
Documentation to be updated? `AddOrUpdate...`

### ISSUE THREAD

**Issue by rwvandenberg** [DalSoft/DalSoft.Swagger.DocumentCodeWithCode#1]
First, thank you @DalSoft . This has project has been a huge help. I really appreciate you sharing this.

I see that there is now a Swashbuckle RC but have not had a chance to review it. If that RC now makes this comment moot, please ignore. 

FYI, my `project.json` references `"Swashbuckle": "6.0.0-beta902"`.

This project's `README.md` file examples reference `operation.Responses.AddOrUpdateResponses(...)` but I believe this should instead be  `operation.Responses.AddOrUpdate(...)` .

Thank you again!

**Comment by DalSoft** [comment]
Thanks @rwvandenberg just corrected this as it was a typo :)
